S01_Activity/S01_Activity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django_practice/', include('django_practice.urls'))
]

S01_Activity/django_practice/urls.py
from django.urls import path
from . import views


app_name = "groceryapp"

urlpatterns = [
    path('index', views.index, name='index'),
    path('<int:groceryitem_id>/', views.groceryitem, name="viewgroceryitem"),
    path('register', views.register, name="register"),
    path('change_password', views.change_password, name="change_password"),
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('add_grocery_item', views.add_grocery_item, name="add_grocery_item")
]

S01_Activity/django_practice/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

# 1


class GroceryItem(models.Model):
    item_name = models.CharField(max_length=50)
    quantity = models.CharField(max_length=50, default="")
    category = models.CharField(max_length=50)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField("date_created")
    user = models.ForeignKey(User, on_delete=models.RESTRICT, default=None)

S01_Activity/django_practice/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="username", max_length=20)
    password = forms.CharField(label="password", max_length=20)


class RegisterForm(forms.Form):
    username = forms.CharField(label="username", max_length=20)
    password = forms.CharField(label="password", max_length=20)
    email = forms.CharField(label="email", max_length=20)
    first_name = forms.CharField(label="first_name", max_length=20)
    last_name = forms.CharField(label="last_name", max_length=20)


class AddGroceryForm(forms.Form):
    item_name = forms.CharField(label="item_name", max_length=50)
    quantity = forms.CharField(label="quantity", max_length=50)
    category = forms.CharField(label="category", max_length=50)


class ChangePasswordForm(forms.Form):
    password = forms.CharField(label="password", max_length=50)
    new_password = forms.CharField(label="new_password", max_length=50)
    re_password = forms.CharField(label="re_password", max_length=50)

S01_Activity/django_practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

# local imports
from .models import GroceryItem
# django import
from django.template import loader

# For Authentication/Register Imports

from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.hashers import make_password

# For conversion of models to a dictionary

from django.forms.models import model_to_dict

# For forms imports

from .forms import LoginForm, RegisterForm, AddGroceryForm

from django.utils import timezone

# Create your views here.


def index(request):

    groceryitem_list = GroceryItem.objects.filter(user_id=request.user.id)
    context = {
        'groceryitem_list': groceryitem_list,
        'user': request.user
    }
    return render(request, "index.html", context)


def groceryitem(request, groceryitem_id):
    # response = f"This is your Grocery Item {groceryitem_id} Details"

    groceryitem = get_object_or_404(GroceryItem, pk=groceryitem_id)

    return render(request, 'groceryitem.html', model_to_dict(groceryitem))


def register(request):
    context = {}

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid() == False:
            form = RegisterForm()

        else:

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']

        duplicates = User.objects.filter(username=username)

        if not duplicates:

            User.objects.create(username=username,
                                first_name=first_name,
                                last_name=last_name,
                                password=make_password(password),
                                email=email,
                                is_staff=False,
                                is_active=True,
                                date_joined=timezone.now()
                                )

            return redirect('groceryapp:login')

        else:
            context = {
                'error': True
            }

    return render(request, "register.html", context)


def change_password(request):

    context = {}

    if request.method == 'POST':

    user = authenticate(username="notadmin123", password="notadmin")

    if user is not None:

        authenticated_user = User.objects.get(username="notadmin123")
        authenticated_user.set_password('notadmin123')
        authenticated_user.save()
        is_user_authenticated = True

    context = {

        'is_user_authenticated': is_user_authenticated
    }

    return render(request, "change_password.html", context)


def login_user(request):

    context = {}

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid() == False:
            form = LoginForm()
        else:
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                context = {
                    'username': username,
                    'password': password
                }
                login(request, user)
                return redirect("groceryapp:index")
            else:
                context = {
                    'error': True
                }

    return render(request, "login.html", context)


def logout_user(request):
    logout(request)
    return redirect("groceryapp:index")


def add_grocery_item(request):
    context = {}

    if request.method == 'POST':
        form = AddGroceryForm(request.POST)

        if form.is_valid() == False:
            form = AddGroceryForm()

        else:
            item_name = form.cleaned_data['item_name']
            quantity = form.cleaned_data['quantity']
            category = form.cleaned_data['category']

        duplicates = GroceryItem.objects.filter(
            item_name=item_name, user_id=request.user.id)

        if not duplicates:
            # Creates an object based on the ToDoItem model and saves to the record in the database

            GroceryItem.objects.create(
                item_name=item_name, quantity=quantity, category=category, date_created=timezone.now(), user_id=request.user.id)

            return redirect("groceryapp:index")

        else:
            context = {
                'error': True
            }

    return render(request, 'add_grocery_item.html', context)

S01_Activity/django_practice/templates/add_grocery_item.html
{% extends "base.html"%}

{% block title%}Add Grocery Item{%endblock%}


{%block content%}


<h1 class="text-center my-3">Add your grocery item:</h1>

<div class="container">

    <div class="row">
        <div class="col-6 offset-3 my-3">
            {% if error == True%}
            <p class=" text-center text-warning">Grocery item already exists.</p>
            {%endif%}
            <form action="{%url 'groceryapp:add_grocery_item' %}" method='POST'>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="item_name" class="form-label">Item Name:</label>
                    <input type="text" class="form-control" id="item_name" placeholder="Enter item name"
                        name="item_name" value="{{item_name}}" maxlength="50" required>
                </div>
                <div class="mb-3">
                    <label for="quantity" class="form-label">Quantity: </label>
                    <input type="text" class="form-control" id="quantity" placeholder="Enter quantity" name="quantity"
                        value="{{quantity}}" maxlength="50" required>
                </div>
                <div class="mb-3">
                    <label for="category" class="form-label">Category: </label>
                    <input type="text" class="form-control" id="category" rows="3" placeholder="Enter category"
                        name="category" value="{{category}}" maxlength="50" required></input>
                </div>
                <div class="text-center">
                    <input class="btn bg-success-subtle border border-success" type="submit" value="Add Item">
                </div>
            </form>
        </div>
    </div>
</div>


{%endblock%}

S01_Activity/django_practice/templates/change_password.html
{%extends "base.html"%}

{%block title%}Register{%endblock%}

{%block content%}
<h1 class="text-center my-3">Change Password</h1>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            {% if error == True%}
            <p class="text-danger">Password do not match is already in use.</p>
            {%endif%}
            <form action="{%url 'groceryapp:change_password'%}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="password" class="form-label">Current Password:</label>
                    <input type="text" class="form-control" id="password" value="{{password}}" maxlength="20"
                        name="password" required>
                </div>
                <div class="mb-3">
                    <label for="new_password" class="form-label">New Password:</label>
                    <input type="text" class="form-control" id="new_password" value="{{new_password}}" maxlength="20"
                        name="new_password" required>
                </div>
                <div class="mb-3">
                    <label for="re_password" class="form-label">Re-Enter New Password</label>
                    <input type="re_password" class="form-control" id="re_password" value="{{re_password}}"
                        maxlength="20" name="re_password" required>
                </div>
                <button type="submit" class="btn btn-primary">Change Password</button>
            </form>
        </div>
    </div>
</div>



{%endblock%}

S01_Activity/django_practice/templates/groceryitem.html
<h1>{{item_name}}</h1>
<h3>Quantity:</h3>
<p>{{quantity}}</p>
<h3>Category:</h3>
<p>{{category}}</p>
<h3>Status:</h3>
<p>{{status}}</p>

<a href="{%url 'groceryapp:index' %}">Back to index page.</a>

S01_Activity/django_practice/templates/index.html
{% extends "base.html"%}

{% block content%}


{% if groceryitem_list and user.is_anonymous == False %}
<h1 class="text-center my-3"> Welcome {{user.first_name}} {{user.last_name}}</h1>

<div class="container">
    <div class="row text-center">
        <!-- <div class="col-3 border border-secondary bg-success-subtle">Grocery item</div>
        <div class="col-3  border border-secondary bg-success-subtle">Quantity</div>
        <div class="col-3 border border-secondary bg-success-subtle">Category</div>
        <div class="col-3 border border-secondary bg-success-subtle">Status</div> -->
        {% for groceryitem in groceryitem_list %}
        <!-- <div class="col-3  border border-secondary"><a class="text-decoration-none"
                href="{%url 'groceryapp:viewgroceryitem' groceryitem.id%}">{{groceryitem.item_name}}</a></div>
        <div class="col-3  border border-secondary">{{groceryitem.quantity}}</div>
        <div class="col-3  border border-secondary">{{groceryitem.category}}</div>
        <div class="col-3  border border-secondary">{{groceryitem.status}}</div> -->
        <div class="card mx-3 border border-secondary" style="width: 25rem;">
            <div class="card-body">
                <h5 class="card-title">{{groceryitem.item_name}}</h5>
                <p class="card-text"></p>
            </div>
            <ul class="list-group list-group-flush ">
                <li class="list-group-item">Quantity: {{groceryitem.quantity}}</li>
                <li class="list-group-item">Category: {{groceryitem.category}}</li>
                <li class="list-group-item">Status: {{groceryitem.status}}</li>
            </ul>
            <div class="card-body">
                <a href="{%url 'groceryapp:viewgroceryitem' groceryitem.id%}" class="card-link text-decoration-none ">Go
                    to item view</a>
            </div>
        </div>
        {% endfor%}
    </div>

</div>


{% elif groceryitem_list.count == 0 and user.is_anonymous == False%}
<h1 class="text-center my-3"> Welcome {{user.first_name}} {{user.last_name}}</h1>
<p class="text-center my-3">No tasks have been created.</p>

{%else%}
<h1 class="text-center my-3">You are not authorized to access this page.</h1>
<p class="text-center my-3">Please login <a href="{% url 'groceryapp:login' %}">here.</a></p>
{% endif %}

{%endblock%}

S01_Activity/django_practice/templates/login.html
{%extends "base.html"%}

{%block title%}Login{%endblock%}

{%block content%}
<h1 class="text-center my-3">Login Form</h1>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            {% if error == True %}
            <p class="text-danger">Invalid credentials, please check your username and password or register first.</p>
            {%endif%}
            <form action="{%url 'groceryapp:login'%}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" id="username" value="{{username}}" maxlength="20"
                        name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" value="{{password}}" maxlength="20"
                        name="password" required>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>



{%endblock%}

S01_Activity/django_practice/templates/register.html
{%extends "base.html"%}

{%block title%}Register{%endblock%}

{%block content%}
<h1 class="text-center my-3">Registration Form</h1>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            {% if error == True%}
            <p class="text-danger">Username is already in use.</p>
            {%endif%}
            <form action="{%url 'groceryapp:register'%}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" id="username" value="{{username}}" maxlength="20"
                        name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" value="{{password}}" maxlength="20"
                        name="password" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email:</label>
                    <input type="text" class="form-control" id="email" value="{{email}}" maxlength="20" name="email"
                        required>
                </div>
                <div class="mb-3">
                    <label for="first_name" class="form-label">First Name:</label>
                    <input type="text" class="form-control" id="first_name" value="{{first_name}}" maxlength="20"
                        name="first_name" required>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name:</label>
                    <input type="text" class="form-control" id="last_name" value="{{last_name}}" maxlength="20"
                        name="last_name" required>
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
        </div>
    </div>
</div>



{%endblock%}

S01_Activity/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}django_practice{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

</head>

<body>
    {%include "navbar.html"%}



    {%block content%}



    {%endblock%}




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
        crossorigin="anonymous"></script>
</body>

</html>

S01_Activity/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-primary-subtle border border-secondary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'groceryapp:index' %}">Grocery List PH</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'groceryapp:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'groceryapp:add_grocery_item'%}">Add Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'groceryapp:index' %}">Check List</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Dropdown link
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{%url 'groceryapp:register'%}">Register</a></li>
                        <li><a class="dropdown-item" href="{%url 'groceryapp:change_password'%}">Change Password</a>
                        </li>
                        <li><a class="dropdown-item" href="{%url 'groceryapp:login'%}">Login</a></li>
                        <li><a class="dropdown-item" href="{%url 'groceryapp:logout'%}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>