discussion/discussion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

discussion/todolist/urls.py
from django.urls import path

# Import the views.py from the same folder
from . import views

app_name = 'todolist'

urlpatterns = [
    path('index', views.index, name='index'),
    path('task/<int:todoitem_id>/', views.todoitem, name="viewtodoitem"),
    path('register', views.register, name="register"),
    path('update_user', views.update_user, name="update_user"),
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('add_task', views.add_task, name="add_task"),
    path('<int:todoitem_id>/update_task',
         views.update_task, name="update_task"),
    path('<int:todoitem_id>/delete', views.delete_task, name="delete_task"),
    path('add_event', views.add_event, name="add_event"),
    path('event/<int:eventitem_id>/', views.eventitem, name="vieweventitem")

]

discussion/todolist/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class ToDoItem(models.Model):
    task_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField('date created')
    # For foreign key use models.ForeignKey(<Model_name>, other_arguements)
    user = models.ForeignKey(User, on_delete=models.RESTRICT, default="")


class EventItem(models.Model):
    event_name = models.CharField(max_length=50)
    event_time = models.CharField(max_length=50, default="")
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="on going")
    date_created = models.DateTimeField('date created')
    # For foreign key use models.ForeignKey(<Model_name>, other_arguements)
    user = models.ForeignKey(User, on_delete=models.RESTRICT, default="")

discussion/todolist/forms.py
# Getter of values for forms that is rendered in html/website

from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="username", max_length=20)
    password = forms.CharField(label="password", max_length=20)


class AddTaskForm(forms.Form):
    task_name = forms.CharField(label="task_name", max_length=50)
    description = forms.CharField(label="description", max_length=200)


class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label="task_name", max_length=50)
    description = forms.CharField(label="description", max_length=200)
    status = forms.CharField(label="status", max_length=50)


class RegisterForm(forms.Form):
    username = forms.CharField(label="username", max_length=20)
    password = forms.CharField(label="password", max_length=20)
    con_password = forms.CharField(label="con_password", max_length=20)
    email = forms.CharField(label="email", max_length=20)
    first_name = forms.CharField(label="first_name", max_length=20)
    last_name = forms.CharField(label="last_name", max_length=20)


class UpdateUserForm(forms.Form):
    first_name = forms.CharField(
        label="first_name", max_length=50)
    last_name = forms.CharField(
        label="last_name", max_length=50)
    password = forms.CharField(label="password", max_length=20)
    new_password = forms.CharField(
        label="new_password", max_length=20, required=False)
    re_password = forms.CharField(
        label="re_password", max_length=20, required=False)


# Event Feature


class AddEventForm(forms.Form):
    event_name = forms.CharField(label="event_name", max_length=50)
    event_time = forms.CharField(label="event_time", max_length=50)
    description = forms.CharField(label="description", max_length=200)

discussion/todolist/views.py
# For django shortcuts render, redirect
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.hashers import make_password, check_password
# Create your views here.

# The from keyword allows importing of necessary classes/modules, methods and other files needed in our application from the django.http package while the import keyword defines what we are importing from the package.

from django.http import HttpResponse

# Local imports
from .models import ToDoItem, EventItem

# import for the built in User Model

from django.contrib.auth.models import User

# to use the template created:
# from django.template import loader

# import for the built in Authenticate Function, Login Function, Logout Function
from django.contrib.auth import authenticate, login, logout

# import for models changing model to a dictionary data
from django.forms.models import model_to_dict

# import for todolis forms

from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, UpdateUserForm

# import for event forms

from .forms import AddEventForm

# django utilities

from django.utils import timezone


def index(request):
    # ToDoItem and EventItem
    todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
    eventitem_list = EventItem.objects.filter(user_id=request.user.id)
    # template = loader.get_template("index.html") - Long cut
    context = {
        'todoitem_list': todoitem_list,
        'eventitem_list': eventitem_list,
        "user": request.user
    }
    # output = ", ".join([todoitem.task_name for todoitem in todoitem_list])
    # render(request, route_template, context)
    return render(request, "index.html", context)


def todoitem(request, todoitem_id):
    # response = f"You are viewing the details of {todoitem_id}"
    # return HttpResponse(response)

    todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
    return render(request, "todoitem.html", model_to_dict(todoitem))

# This function is responsible for registering on our application.


def register(request):

    context = {}

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid() == False:
            form = RegisterForm()

        else:
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            con_password = form.cleaned_data['con_password']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']

        duplicates = User.objects.filter(username=username)

        if not duplicates and (con_password == password):

            User.objects.create(username=username,
                                first_name=first_name,
                                last_name=last_name,
                                password=make_password(password),
                                email=email,
                                is_staff=False,
                                is_active=True,
                                date_joined=timezone.now()
                                )

            return redirect('todolist:login')

        else:
            context = {
                'error': True
            }

    return render(request, "register.html", context)


def update_user(request):

    context = {}

    user = get_object_or_404(User, pk=request.user.id)

    context = {
        'first_name': user.first_name,
        'last_name': user.last_name
    }

    if request.method == 'POST':
        form = UpdateUserForm(request.POST)

        if form.is_valid() == False:
            form = UpdateUserForm()
        else:
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            password = form.cleaned_data['password']
            new_password = form.cleaned_data['new_password']
            re_password = form.cleaned_data['re_password']

            if user and check_password(password, request.user.password):
                user.first_name = first_name
                user.last_name = last_name
                if new_password and re_password and (new_password == re_password):
                    user.password = make_password(new_password)
                    user = authenticate(username=user.username,
                                        password=new_password)
                    login(request, user)

                user.save()
                return redirect('todolist:index')
            else:
                context = {
                    'error': True
                }

    return render(request, "update_user.html", context)


def login_user(request):

    context = {}

    # if this is a POST request we nee to process the form data

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid() == False:
            form = LoginForm()
        else:
            # cleaned_data is a method to get/retrieves the properties or information that was entered in the form.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                context = {
                    'username': username,
                    'password': password
                }
                login(request, user)
                return redirect("todolist:index")
            else:
                context = {
                    'error': True
                }

    return render(request, "login.html", context)
    # username = form.username
    # password = 'jane1234'

    # user = authenticate(username=username, password=password)

    # if user is not None:
    #     login(request, user)
    #     return redirect("todolist:index")


def logout_user(request):
    logout(request)
    return redirect("todolist:index")


def add_task(request):
    context = {}

    if request.method == 'POST':
        form = AddTaskForm(request.POST)

        if form.is_valid() == False:
            form = AddTaskForm()

        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']

        duplicates = ToDoItem.objects.filter(
            task_name=task_name, user_id=request.user.id)

        if not duplicates:
            # Creates an object based on the ToDoItem model and saves to the record in the database

            ToDoItem.objects.create(
                task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)

            return redirect("todolist:index")

        else:
            context = {
                'error': True
            }

    return render(request, 'add_task.html', context)


def update_task(request, todoitem_id):

    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    context = {
        "user": request.user,
        'todoitem_id': todoitem_id,
        "task_name": todoitem[0].task_name,
        "description": todoitem[0].description,
        "status": todoitem[0].status
    }

    if request.method == 'POST':
        form = UpdateTaskForm(request.POST)

        if form.is_valid() == False:
            form = UpdateTaskForm()

        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']

            if todoitem:
                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status

                todoitem[0].save()

                return redirect("todolist:viewtodoitem", todoitem_id=todoitem[0].id)

            else:
                context = {
                    'error': True
                }
    return render(request, "update_task.html", context)


def delete_task(request, todoitem_id):

    ToDoItem.objects.filter(pk=todoitem_id).delete()

    return redirect("todolist:index")


# Events


def add_event(request):
    context = {}

    if request.method == 'POST':
        form = AddEventForm(request.POST)

        if form.is_valid() == False:
            form = AddEventForm()

        else:
            event_name = form.cleaned_data['event_name']
            event_time = form.cleaned_data['event_time']
            description = form.cleaned_data['description']

        duplicates = EventItem.objects.filter(
            event_name=event_name, user_id=request.user.id)

        if not duplicates:
            # Creates an object based on the ToDoItem model and saves to the record in the database

            EventItem.objects.create(
                event_name=event_name, event_time=event_time, description=description, date_created=timezone.now(), user_id=request.user.id)

            return redirect("todolist:index")

        else:
            context = {
                'error': True
            }

    return render(request, 'add_event.html', context)


def eventitem(request, eventitem_id):

    eventitem = get_object_or_404(EventItem, pk=eventitem_id)

    return render(request, "eventitem.html", model_to_dict(eventitem))

discussion/todolist/templates/add_event.html
{% extends 'base.html'%}

{%block title%}Add Event{%endblock%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">

            {% if error == True%}
            <p class="text-danger">Event already ongoing.</p>
            {%endif%}
            <form action="{% url 'todolist:add_event' %}" method="POST">

                {% csrf_token %}

                <div class="mb-3">
                    <label for="event_name">Event Name: </label>
                    <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}"
                        maxlength="50" required>
                </div>
                <div class="mb-3">
                    <label for="event_time">Event Time: </label>
                    <input class="form-control" id="event_time" type="text" name="event_time" value="{{ event_time }}"
                        maxlength="50" required>
                </div>
                <div class="mb-3">
                    <label for="description">Description: </label>
                    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                </div>

                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Start Event">
                </div>

            </form>
        </div>
    </div>
</div>


{%endblock%}

discussion/todolist/templates/add_task.html
{% extends 'base.html'%}

{%block title%}Add Task{%endblock%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">

            {% if error == True%}
            <p class="text-danger">Duplicate task found.</p>
            {%endif%}
            <form action="{% url 'todolist:add_task' %}" method="POST">

                {% csrf_token %}

                <div class="mb-3">
                    <label for="task_name">Task Name: </label>
                    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}"
                        maxlength="50" required>
                </div>

                <div class="mb-3">
                    <label for="description">Description: </label>
                    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                </div>

                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Add Task">
                </div>

            </form>
        </div>
    </div>
</div>


{%endblock%}

discussion/todolist/templates/eventitem.html
{% extends "base.html"%}

{% block title %}My Events{%endblock%}


{% block content%}

<div class="text-center mt-3">
    <h1>{{event_name}}</h1>
    <h3>When:</h3>
    <p>{{When}}</p>
    <h3>Description:</h3>
    <p>{{description}}</p>
    <h3>Status:</h3>
    <p>{{status}}</p>

    <button class=" btn bg-warning-subtle mx-1 border border-secondary"><a class=" text-decoration-none text-secondary"
            href="{%url 'todolist:index'%}">Back to
            index
            page.</a></button>
</div>





{%endblock%}

discussion/todolist/templates/index.html
{%extends "base.html" %}

{%block title%}Home{%endblock%}

{%block content%}
{%if user.is_anonymous == False %}
{% if todoitem_list%}
<h1 class="text-center my-3"> Welcome {{user.first_name}} {{user.last_name}}</h1>

<div class="container">
    <div class="row">
        <h3 class="text-center mb-3">My Tasks</h3>
        {% for todoitem in todoitem_list %}
        <div class="card mx-3 border border-secondary" style="width: 25rem;">
            <div class="card-body">
                <h5 class="card-title">{{todoitem.task_name}}</h5>
                <p class="card-text"></p>
            </div>
            <ul class="list-group list-group-flush ">
                <li class="list-group-item">Quantity: {{todoitem.description}}</li>
                <li class="list-group-item">Status: {{todoitem.status}}</li>
            </ul>
            <div class="card-body text-center">
                <button class="btn bg-danger-subtle">
                    <a href="{% url 'todolist:viewtodoitem' todoitem.id%}"
                        class="card-link text-decoration-none text-secondary">Check
                        Task</a>
                </button>
            </div>
        </div>
        {% endfor%}
    </div>
</div>

{%else%}
<h1 class="text-center my-3"> Welcome {{user.first_name}} {{user.last_name}}</h1>
<h3 class="text-center mb-3">My Tasks</h3>
<p class="text-center my-3">No tasks have been created.</p>

{% endif %}

{% if eventitem_list%}

<div class="container">
    <div class="row">
        <h3 class="text-center mb-3">My Events</h3>
        {% for eventitem in eventitem_list %}
        <div class="card mx-3 border border-secondary" style="width: 25rem;">
            <div class="card-body">
                <h5 class="card-title">{{eventitem.event_name}}</h5>
                <p class="card-text"></p>
            </div>
            <ul class="list-group list-group-flush ">
                <li class="list-group-item">When: {{eventitem.event_time}}</li>
                <li class="list-group-item">Description: {{eventitem.description}}</li>
                <li class="list-group-item">Status: {{eventitem.status}}</li>
            </ul>
            <div class="card-body text-center">
                <button class="btn bg-primary-subtle">
                    <a href="{%url 'todolist:vieweventitem' eventitem.id%}"
                        class="card-link text-decoration-none text-secondary">Check
                        Event</a>
                </button>
            </div>
        </div>
        {% endfor%}
    </div>
</div>

{% else%}
<h3 class="text-center mb-3">My Events</h3>
<p class="text-center my-3">No ongoing events.</p>
{% endif %}
{% else%}
<h1 class="text-center my-3">You are not authorized to access this page.</h1>
<p class="text-center my-3">Please login <a href="{% url 'todolist:login' %}">here.</a></p>
{% endif %}

{%endblock%}

discussion/todolist/templates/login.html
{%extends "base.html"%}


{%block title%}Login{%endblock%}

{% block content %}


<h1 class="text-center my-3">Login Form</h1>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            {% if error == True %}
            <p class="text-danger">Invalid credentials, please check your username and password or register first.</p>
            {%endif%}
            <form action="{%url 'todolist:login' %}" method="POST">
                <!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
                <!-- CSRF occurs when a malicious website contains link, a form button or some JavaScript that is intended to perform in some action in our website -->
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" id="username" value="{{username}}" name="username"
                        maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="paswword" class="form-label">Password:</label>
                    <input type="password" class="form-control" id="paswword" value="{{password}}" name="password"
                        maxlength="20" required>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>

</div>


{%endblock%}

discussion/todolist/templates/register.html
{%extends "base.html"%}

{%block title%}Register{%endblock%}

{%block content%}
<h1 class="text-center my-3">Registration Form</h1>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            {% if error == True%}
            <p class="text-danger">Username is already in use or password is unmatched.</p>
            {%endif%}
            <form action="{%url 'todolist:register'%}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" id="username" value="{{username}}" maxlength="20"
                        name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" class="form-control" id="password" value="{{password}}" maxlength="20"
                        name="password" required>
                </div>
                <div class="mb-3">
                    <label for="con_password" class="form-label">Confirm Password:</label>
                    <input type="password" class="form-control" id="con_password" value="{{con_password}}"
                        maxlength="20" name="con_password" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email:</label>
                    <input type="text" class="form-control" id="email" value="{{email}}" maxlength="20" name="email"
                        required>
                </div>
                <div class="mb-3">
                    <label for="first_name" class="form-label">First Name:</label>
                    <input type="text" class="form-control" id="first_name" value="{{first_name}}" maxlength="20"
                        name="first_name" required>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name:</label>
                    <input type="text" class="form-control" id="last_name" value="{{last_name}}" maxlength="20"
                        name="last_name" required>
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
        </div>
    </div>
</div>



{%endblock%}

discussion/todolist/templates/todoitem.html
{% extends "base.html"%}

{% block title %}My Tasks{%endblock%}


{% block content%}

<div class="text-center mt-3">
    <h1>{{task_name}}</h1>
    <h3>Description:</h3>
    <p>{{description}}</p>
    <h3>Status:</h3>
    <p>{{status}}</p>
    <button class="btn bg-success-subtle mx-1 border border-secondary"><a class="text-decoration-none text-secondary"
            href="{%url 'todolist:update_task' id%}">Edit this
            Task</a></button>

    <button class="btn bg-danger-subtle mx-1 border border-secondary"><a class="text-decoration-none text-secondary"
            href="{%url 'todolist:delete_task' id%}">Delete this
            Task</a></button>

    <button class=" btn  bg-warning-subtle mx-1 border border-secondary"><a class=" text-decoration-none text-secondary"
            href="{%url 'todolist:index'%}">Back to
            index
            page.</a></button>
</div>





{%endblock%}

discussion/todolist/templates/update_task.html
{% extends "base.html" %}

{%block title%} Update Task {%endblock%}

{%block content%}
{%if user.is_anonymous == False %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center t-2">Update Task</h1>
            {% if error == True%}
            <p class="text-danger">Task Not Found</p>
            {%endif%}
            <form action="{% url 'todolist:update_task' todoitem_id %}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="task_name">Task Name: </label>
                    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}"
                        maxlength="50" required>
                </div>
                <div class="mb-3">
                    <label for="description">Description: </label>
                    <textarea class="form-control" name="description" required>{{ description }}</textarea>
                </div>
                <div class="mb-3">
                    <label for="status">Status: </label>
                    <input class="form-control" id="status" type="text" name="status" value="{{ status }}"
                        maxlength="50" required>
                </div>
                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Update Task">
                </div>
            </form>
        </div>
    </div>
</div>
{%endif%}


{% endblock %}

discussion/todolist/templates/update_user.html
{%extends "base.html"%}

{%block title%}Update User{%endblock%}

{%block content%}
{%if user.is_anonymous == False %}
<h1 class="text-center my-3">Update User</h1>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            {% if error == True%}
            <p class="text-danger">Password do not match.</p>
            {%endif%}
            <form action="{%url 'todolist:update_user'%}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="first_name" class="form-label">First Name:</label>
                    <input type="text" class="form-control" id="first_name" value="{{first_name}}" maxlength="20"
                        name="first_name" required>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name:</label>
                    <input type="text" class="form-control" id="last_name" value="{{last_name}}" maxlength="20"
                        name="last_name" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Current Password:</label>
                    <input type="password" class="form-control" id="password" value="{{password}}" maxlength="20"
                        name="password" required>
                </div>
                <div class="mb-3">
                    <label for="new_password" class="form-label">New Password:</label>
                    <input type="password" class="form-control" id="new_password" value="{{new_password}}"
                        maxlength="20" name="new_password">
                </div>
                <div class="mb-3">
                    <label for="re_password" class="form-label">Re-Enter New Password</label>
                    <input type="password" class="form-control" id="re_password" value="{{re_password}}" maxlength="20"
                        name="re_password">
                </div>
                <button type="submit" class="btn btn-primary">Update User</button>
            </form>
        </div>
    </div>
</div>
{%endif%}


{%endblock%}